IMAGE_NAME = "centos/7"
IP = "192.168.219.33"
HOSTNAME = "aws-cli"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define HOSTNAME do |cfg|
    cfg.vm.box = IMAGE_NAME
    cfg.vm.network "public_network", ip: IP
    cfg.vm.hostname = HOSTNAME
    
    cfg.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 4
      v.name = HOSTNAME
    end

    cfg.vm.provision "shell", inline: <<-SCRIPT
      yum install epel-release -y
      yum install unzip -y
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
    SCRIPT
  end
end